# Generated by Django 3.0.3 on 2021-01-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200705_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mycv', models.FileField(upload_to='mycv')),
            ],
        ),
    ]
